services:

  masterpoint_service:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - masterpoint_db
  
  masterpoint_db:
    image: postgres:15
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=masterpoint_service


volumes:
  postgres_data: