# Generated by Django 5.2 on 2025-04-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0001_initial'),
        ('employees', '0005_alter_employee_cpf_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Funcionário'),
        ),
    ]
