# Generated by Django 5.2 on 2025-04-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0002_alter_clock_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='clock',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
    ]
